### ISSUE TITLE
HTML without article element prints empty index.md

### ISSUE THREAD

**Issue by infominer33** [Ruined1/HTMLArticleElementStripper#1]
prints empty index.md file for files for html without <article></article>

fyi.

super duper tho! ran the 2000+ files in a breeze

**Comment by DeeJayhX** [comment]
Will patch that out! Thanks!

**Comment by DeeJayhX** [comment]
Fixed in [latest commit](https://github.com/Ruined1/HTMLArticleElementStripper/commit/54a4ee1307c4b7d8fe108853e78e13acef870e69). Lots of new features to check out as well! Thanks!
