### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by infominer33** [Ruined1/HTMLArticleElementStripper#3]
```
vpn-comparison-chart/index.html. Opening... Done.
Traceback (most recent call last):
  File "articlestrip.py", line 50, in <module>
    stripped.insert(0, re.split(">([^<>]+)<", line.strip())[1])
IndexError: list index out of range
```

[index.txt](https://github.com/Ruined1/HTMLArticleElementStripper/files/3169683/index.txt)

same kinda error w this file
[index.txt](https://github.com/Ruined1/HTMLArticleElementStripper/files/3169685/index.txt)

**Comment by infominer33** [comment]
all in all, pretty slick app... except for those 2 files it hiccuped on did just fine

![image](https://user-images.githubusercontent.com/44134283/57577364-f5ae1180-7442-11e9-82b2-ba3925d5067a.png)

**Comment by DeeJayhX** [comment]
This exception was generated using a customized version of this script and doesn't apply to this repository.
